blank_issues_enabled: true
contact_links:
  - name: 💬 Discussions
    url: https://github.com/kur00/issue-templates/discussions
    about: For general questions and discussions
  - name: 🔒 Security Issues
    url: mailto:security@example.com
    about: Please report security vulnerabilities privately